### ISSUE TITLE
Unable to pass `tvOS` platform. Incorrect input type `platform`

### ISSUE THREAD

**Issue by markst** [platanus/bitrise-step-fastlane-match#8]
When using the step the input for Platform is an input for the provisioning profile type:

<img width="257" alt="image" src="https://github.com/user-attachments/assets/d4ff1425-f33f-4deb-bf6f-24074f272fdf" />

Where in actual fact this is the `type` passed to Match.

Platform title should be renamed to 'Type'
New input should be added with type `platform` which allows specifying ios, macos, tvos, catalyst.

This platform should be passed as Match argument 'platform'. i.e:

```shell
fastlane match appstore --platform tvos --readonly
```

**Comment by markst** [comment]
So it should be like this:


```yaml
  - type: development
    opts:
      title: "Certificate Type"
      summary: ""
      description: |-
        The type of certificate and provisioning profile you want to install.
      is_required: true
      value_options:
      - "adhoc"
      - "appstore"
      - "development"
      - "enterprise"
  - platform: ios
    opts:
      title: "Platform"
      summary: ""
      description: |-
        The platform for which the certificate and provisioning profile should be installed.
      is_required: true
      value_options:
      - "ios"
      - "tvos"
      - "macos"
      - "catalyst"
```
